apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2
spec:
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginxmaster
  replicas: 2
  selector:
    matchLabels:
      tier: frontend